### ISSUE TITLE
[1.12.2] Bug with Iguana Tweaks Reborn Poison option

### ISSUE THREAD

**Issue by pimalel233** [SlimeKnights/Mantle#130]
## Versions
- **Scaling Health**:1.3.42+147
- **Silent Lib**: 3.0.13+168
OR
+ **Mantle 1.3.3.55

- **Forge**: 14.23.5.2838
- **Modpack**:  N/A
- **Optifine Installed**: Does not matter
- **IguanaTweaks Reborn: 1.4.20

## Expected Behavior
The health bar stays as one bar when poisoned.

## Actual Behavior
The health bar duplicates or second row above first one appears when posioned and IguanaTweaks Reborn has option below set to true.
misc
        # The poison effect will be changed to be deadly and drain hunger, but will damage the player 3 times slower
        B:"Alter Poison"=true

## Links/Images
Scaling Health only:
No poison: http://prntscr.com/qplp9p
Poisoned: http://prntscr.com/qplm87
No posion, custom hearth rendering off: http://prntscr.com/qploze
Custom hearth rendering off+poisoned: http://prntscr.com/qplmg5
*with Scaling Health, if health vanilla or lower, issue does not happen as long as Custom heath rendering is off

Mantle only (health increased with Scaling health, then uninstalled, if health is not higher than vanilla issue does not happen)
Not poisoned: http://prntscr.com/qplvz3
Poisoned: http://prntscr.com/qplw4q

Tried also with Mantle + Scaling Health (Rendering off so Mantle would handle wrapping up rows) and it still bugs out.

## Steps to Reproduce the Problem
1. Install mods mentioned in versions
2. Make sure poison option in IguanaTweaks in misc is set to true
3. Poison yourself

Would be great if 1.12 version could receive some kind of compatibility patch for this option. I tested it few times with everything off in IguanaTweaks and only posion on and it still happens. With the poison off and Hardness/Movement Restriction and rest of the misc section mostly on, so far have not seen it happening again.

I will be reporting it also on other mods pages.
SilentChaos512/ScalingHealth#216
Insane96/IguanaTweaksReborn#97

Thanks for the great mods guys!

**Comment by KnightMiner** [comment]
Not really much we can do to fix this. It looks like they override the health renderer to make it show with their poison effect. It would be pretty easy on their side to just registry replace poison so the vanilla render takes over, or to cancel the event we fire so our renderer does not run when theirs does, but as it stands right now there is nothing we can do on our side.

----

While this is a very good issue report, going to have to close this as its pretty clear this issue is a side effect of both our renderers running at the same time, and there really is nothing we can do detect Iguana Tweaks's and stop their renderer if they are no longer maintained for 1.12. If this was reported a few months earlier we might be able to do more as fewer mods would be in end of life for 1.12.
