### ISSUE TITLE
[1.18.2] Crash upon attempt to render creative decorations inventory screen 

### ISSUE THREAD

**Issue by caniplzjustlogin4godsakesthistakesforev** [SlimeKnights/Mantle#192]
[crash-2022-12-27_12.06.41-client.txt](https://github.com/SlimeKnights/Mantle/files/10310048/crash-2022-12-27_12.06.41-client.txt)
[latest.log](https://github.com/SlimeKnights/Mantle/files/10310049/latest.log)
Not sure if this crash is caused by Mantle or if mantle is just catching an error caused by another mod, if it is it's probably something to do with Every Compat (Wood Good)

**Comment by KnightMiner** [comment]
Caused by another mod, someone has a broken model with no particle texture. Mantle probably should catch that as mods doing stupid things is surprisingly common.

Looks like the only mod you have installed that uses that model is Inspirations, so its either some mods leaves or wooden slabs with the broken model. I could see Every Compat doing something but I suggest spending some time removing mods to find out which is to blame.

**Comment by KnightMiner** [comment]
Mantle 1.9.50 catches that potential crash
