### ISSUE TITLE
Missing Chars when using with the ModernUI

### ISSUE THREAD

**Issue by Cactusstudent** [SlimeKnights/Mantle#195]
Mantle Version: `1.9.43`
ModernUI Version: `3.5.4.113`
Other Mods: `Tconstruct ( 3.6.2.92 )` ; `Just Enough Item ( 9.7.2.1001 )`
Can Reproduce.

When installing both Mantle and modernUI, the guide book will missing some characters, like this
actual text: Mattoc
correct text: Mattock
![image](https://user-images.githubusercontent.com/97865546/214862687-8bf0a06c-5bc7-47d5-a217-1a5dd1bee367.png)
Could you add support to this mod? thanks a lot.

**Comment by Cactusstudent** [comment]
Have post to ModernUI, see [#129](https://github.com/BloCamLimb/ModernUI/issues/129)
The Author says:
这就和 Modern UI 没有关系了，有些模组会自己做多行布局，兼容很差。
(Use Machine Translate) This has nothing to do with Modern UI, some modules will do much line layout, compatibility is poor.

**Comment by KnightMiner** [comment]
The issue here is that mod is changing our font, but in a hacky way such that the functions that get the text width no longer work. Entirely on them, they are flat out wrong that its not their problem

Plus, they should absolutely not be changing our font. I recommend going back to Modern UI and telling them that they are breaking the functions in fonts that detect the text width. If they refuse to do anything, then uninstall that mod as I really doubt it will be just Tinkers' it breaks.

**Comment by Cactusstudent** [comment]
Have resolved by configure some settings, thanks

**Comment by Falgar** [comment]
Any chance you can share what config settings you changed to resolve the issue?
