### ISSUE TITLE
Question about a PR to possibly port tconstruct to 1.20.1 temporarely for our pack

### ISSUE THREAD

**Issue by MageOfGaming** [SlimeKnights/Mantle#214]
Hey so I wanted to reach out in the name of one of our devs from our pretty ambitious modpack, and we've encountered a small issue and wanted to ask  some things, so if you got a minute that would be really great. So essentially we are updating our pack from 1.18.2 to 1.20.1 which means tconstruct isn't for the same version but is essential for the pack and our companion mods, so our dev looked at it and it seems to possible to make a temporary fork for our pack if this pr for mantle would get accepted; https://github.com/SlimeKnights/Mantle/pull/211

And on the same note I'd like to ask if it would be fine if we made a temporary 1.20.1 tconstruct port for our in-dev pack until possibly a official version is released and if not, if we could maintain that for ourselves and what you're terms would be with that, of course we would also clearly separate the two by mod id and name everywhere it's possible, would this be any issue to you?

**Comment by KnightMiner** [comment]
We have talked on discord about this. Short version is yes, I will port mods. I just don't have unlimited free time. And its more work for someone else to port the mod for me typically than me just porting it myself.

There are quite a few things that need to be finished before a 1.20 port is attempted, help with those would help the process faster.

----

As an aside, this whole series of issues from this group sounds a lot like "we already did this, and we would like to ask permission after the fact" instead of "what is the best way to do this?", feels too much like I am being pressured with threats of "we will fork the mod if you don't listen" and not enough like you actually care to better the mod.

We make open source mods, there is no reason you can't talk to each other before you take extreme actions. Forking the mod creates so, so much more work for me than just helping the mod get finished. I am always against forks of actively maintained mods outside of areas I have specifically noted I will not support (e.g. Fabric), 1.20 is not one such area.

I get that you want to make a mod pack, but if you really so desperately need my mod for the pack to work, then make it on a version I support already or be patient for me to have free time to port it. I will never condone a public fork of my mod unless I have stated its abandoned.
