### ISSUE TITLE
Is Mantle ready or available for 1.8

### ISSUE THREAD

**Issue by KingCreeperEli** [SlimeKnights/Mantle#40]
I need a way to add multiple instruction books into my mod and was looking at mantle to do that. When I went to download it and use it in my mod as a dependency, I saw that only 1.7.10 is available and my mod is for 1.8. Is there a 1.8 version available that I can work with now and then switch out when the official version comes out? Is there a way to use what you guys currently have on GitHub under the 1.8 branch to add to my mod? This is really the last step to complete before releasing my mod because my mod is kind of complicated and I like the style mantle uses. Any feedback is appreciated!

Thank you in advance,
-KingCreeperEli

**Comment by bonii-xx** [comment]
No, Mantle is not ready yet and will not be ready for some time. If you only want the books I'd recommend looking somewhere else too, because we're not going to take the old book system with us. The future of the books system is unsure. I'll probably use another one for Tinkers' itself, or adapt an existing one to our needs. But that's pretty much the last thing that will be done.

So in short: Nope, no books for 1.8, sorry.

**Comment by Adaptivity** [comment]
I hope you can look into [Guide-API](http://minecraft.curseforge.com/mc-mods/228832-guide-api). Hope it will be updated to 1.8 when Tinkers' will be updated too :smile:
